"""Change type of match_id from Varchar to Int

Revision ID: 01107af82369
Revises: d177a57abdb0
Create Date: 2025-02-26 13:52:36.696371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01107af82369'
down_revision: Union[str, None] = 'd177a57abdb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coefficients', sa.Column('score1', sa.String(), nullable=True))
    op.add_column('coefficients', sa.Column('score2', sa.String(), nullable=True))
    op.add_column('coefficients', sa.Column('period', sa.String(), nullable=True))
    op.add_column('coefficients', sa.Column('curr_period_status', sa.String(), nullable=True))
    op.add_column('coefficients', sa.Column('quarter_account', sa.JSON(), nullable=True))
    op.add_column('coefficients', sa.Column('time', sa.String(), nullable=True))
    op.alter_column('coefficients', 'match_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_foreign_key(None, 'coefficients', 'matches', ['match_id'], ['match_id'])
    op.alter_column('matches', 'match_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_matches_match_id'), 'matches', ['match_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_match_id'), table_name='matches')
    op.alter_column('matches', 'match_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_constraint(None, 'coefficients', type_='foreignkey')
    op.alter_column('coefficients', 'match_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('coefficients', 'time')
    op.drop_column('coefficients', 'quarter_account')
    op.drop_column('coefficients', 'curr_period_status')
    op.drop_column('coefficients', 'period')
    op.drop_column('coefficients', 'score2')
    op.drop_column('coefficients', 'score1')
    # ### end Alembic commands ###
