"""Change curr_period_status to curr_period_quarter in Matches

Revision ID: 1c95c2cc7527
Revises: d5cf63342aaf
Create Date: 2025-02-26 13:24:09.610644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c95c2cc7527'
down_revision: Union[str, None] = 'd5cf63342aaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('curr_period_quarter', sa.String(), nullable=True))
    op.drop_column('matches', 'curr_period_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('curr_period_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('matches', 'curr_period_quarter')
    # ### end Alembic commands ###
