"""Change name  curr_period_status to curr_quarter

Revision ID: 3c3c6e5bd61c
Revises: d3cf40539389
Create Date: 2025-02-26 14:22:07.749734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c3c6e5bd61c'
down_revision: Union[str, None] = 'd3cf40539389'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coefficients', sa.Column('curr_quarter', sa.String(), nullable=True))
    op.drop_column('coefficients', 'curr_period_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coefficients', sa.Column('curr_period_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('coefficients', 'curr_quarter')
    # ### end Alembic commands ###
