"""Add column cp for Coefficient

Revision ID: a4e5889a6bdd
Revises: 4c8993720d9a
Create Date: 2025-02-27 16:10:25.226740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4e5889a6bdd'
down_revision: Union[str, None] = '4c8993720d9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coefficients', sa.Column('cp', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coefficients', 'cp')
    # ### end Alembic commands ###
