"""Add cps, add_info to Coefficient

Revision ID: b68d98e8a431
Revises: cf1dce655c97
Create Date: 2025-02-25 17:08:33.036865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b68d98e8a431'
down_revision: Union[str, None] = 'cf1dce655c97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coefficients', sa.Column('cps', sa.String(), nullable=True))
    op.add_column('coefficients', sa.Column('add_info', sa.String(), nullable=True))
    op.add_column('matches', sa.Column('league', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'league')
    op.drop_column('coefficients', 'add_info')
    op.drop_column('coefficients', 'cps')
    # ### end Alembic commands ###
