"""Change type of match_id from Varchar to Int

Revision ID: d177a57abdb0
Revises: 130b631074fd
Create Date: 2025-02-26 13:32:11.706589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd177a57abdb0'
down_revision: Union[str, None] = '130b631074fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coefficients', sa.Column('score1', sa.Integer(), nullable=True))
    op.add_column('coefficients', sa.Column('score2', sa.Integer(), nullable=True))
    op.add_column('coefficients', sa.Column('period', sa.String(), nullable=True))
    op.add_column('coefficients', sa.Column('curr_period_status', sa.String(), nullable=True))
    op.add_column('coefficients', sa.Column('quarter_account', sa.JSON(), nullable=True))
    op.add_column('coefficients', sa.Column('time', sa.String(), nullable=True))
    op.alter_column('coefficients', 'match_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
    # op.drop_index('ix_coefficients_market_id', table_name='coefficients')
    # op.drop_constraint('coefficients_block_id_fkey', 'coefficients', type_='foreignkey')
    # op.drop_constraint('coefficients_market_id_fkey', 'coefficients', type_='foreignkey')
    # op.drop_column('coefficients', 'timestamp')
    # op.drop_column('coefficients', 'block_id')
    # op.drop_column('coefficients', 'market_id')
    op.add_column('matches', sa.Column('league', sa.String(), nullable=True))
    op.add_column('matches', sa.Column('status', sa.String(), nullable=True))
    op.add_column('matches', sa.Column('curr_period_quarter', sa.String(), nullable=True))
    op.add_column('matches', sa.Column('additional_info', sa.String(), nullable=True))
    op.add_column('matches', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('matches', 'match_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_column('matches', 'timestamp')
    op.drop_column('matches', 'time')
    op.drop_column('matches', 'score_team1')
    op.drop_column('matches', 'score_team2')
    op.drop_column('matches', 'period')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('period', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('matches', sa.Column('score_team2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('matches', sa.Column('score_team1', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('matches', sa.Column('time', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('matches', sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.alter_column('matches', 'match_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('matches', 'created_at')
    op.drop_column('matches', 'additional_info')
    op.drop_column('matches', 'curr_period_quarter')
    op.drop_column('matches', 'status')
    op.drop_column('matches', 'league')
    op.add_column('coefficients', sa.Column('market_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('coefficients', sa.Column('block_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('coefficients', sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_foreign_key('coefficients_market_id_fkey', 'coefficients', 'markets', ['market_id'], ['market_id'])
    op.create_foreign_key('coefficients_block_id_fkey', 'coefficients', 'blocks', ['block_id'], ['block_id'])
    op.create_index('ix_coefficients_market_id', 'coefficients', ['market_id'], unique=False)
    op.create_index('ix_coefficients_block_id', 'coefficients', ['block_id'], unique=False)
    op.alter_column('coefficients', 'match_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('coefficients', 'time')
    op.drop_column('coefficients', 'quarter_account')
    op.drop_column('coefficients', 'curr_period_status')
    op.drop_column('coefficients', 'period')
    op.drop_column('coefficients', 'score2')
    op.drop_column('coefficients', 'score1')
    # ### end Alembic commands ###
