"""Change type of match_id from Int to Varchar

Revision ID: d3cf40539389
Revises: d1e181ad15d7
Create Date: 2025-02-26 14:04:13.418140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3cf40539389'
down_revision: Union[str, None] = 'd1e181ad15d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.String(), nullable=True),
    sa.Column('league', sa.String(), nullable=True),
    sa.Column('team1', sa.String(), nullable=True),
    sa.Column('team2', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('curr_period_quarter', sa.String(), nullable=True),
    sa.Column('additional_info', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_id'), 'matches', ['id'], unique=False)
    op.create_index(op.f('ix_matches_match_id'), 'matches', ['match_id'], unique=True)
    op.create_table('coefficients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.String(), nullable=True),
    sa.Column('values', sa.JSON(), nullable=True),
    sa.Column('score1', sa.String(), nullable=True),
    sa.Column('score2', sa.String(), nullable=True),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('curr_period_status', sa.String(), nullable=True),
    sa.Column('quarter_account', sa.JSON(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coefficients_id'), 'coefficients', ['id'], unique=False)
    op.create_index(op.f('ix_coefficients_match_id'), 'coefficients', ['match_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coefficients_match_id'), table_name='coefficients')
    op.drop_index(op.f('ix_coefficients_id'), table_name='coefficients')
    op.drop_table('coefficients')
    op.drop_index(op.f('ix_matches_match_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_id'), table_name='matches')
    op.drop_table('matches')
    # ### end Alembic commands ###
