"""Add created_at to matches

Revision ID: d5cf63342aaf
Revises: b68d98e8a431
Create Date: 2025-02-26 12:53:39.732909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5cf63342aaf'
down_revision: Union[str, None] = 'b68d98e8a431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coefficients', sa.Column('curr_period_status', sa.String(), nullable=True))
    op.add_column('coefficients', sa.Column('quarter_account', sa.JSON(), nullable=True))
    op.drop_index('ix_coefficients_block_id', table_name='coefficients')
    op.drop_index('ix_coefficients_market_id', table_name='coefficients')
    op.drop_constraint('coefficients_block_id_fkey', 'coefficients', type_='foreignkey')
    op.drop_constraint('coefficients_market_id_fkey', 'coefficients', type_='foreignkey')
    op.drop_column('coefficients', 'cps')
    op.drop_column('coefficients', 'add_info')
    op.drop_column('coefficients', 'block_id')
    op.drop_column('coefficients', 'market_id')
    op.add_column('matches', sa.Column('curr_period_status', sa.String(), nullable=True))
    op.add_column('matches', sa.Column('additional_info', sa.String(), nullable=True))
    op.add_column('matches', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('matches', 'score_team1')
    op.drop_column('matches', 'time')
    op.drop_column('matches', 'score_team2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('score_team2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('matches', sa.Column('time', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('matches', sa.Column('score_team1', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('matches', 'created_at')
    op.drop_column('matches', 'additional_info')
    op.drop_column('matches', 'curr_period_status')
    op.add_column('coefficients', sa.Column('market_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('coefficients', sa.Column('block_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('coefficients', sa.Column('add_info', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('coefficients', sa.Column('cps', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('coefficients_market_id_fkey', 'coefficients', 'markets', ['market_id'], ['market_id'])
    op.create_foreign_key('coefficients_block_id_fkey', 'coefficients', 'blocks', ['block_id'], ['block_id'])
    op.create_index('ix_coefficients_market_id', 'coefficients', ['market_id'], unique=False)
    op.create_index('ix_coefficients_block_id', 'coefficients', ['block_id'], unique=False)
    op.drop_column('coefficients', 'quarter_account')
    op.drop_column('coefficients', 'curr_period_status')
    # ### end Alembic commands ###
